pipeline {
    agent any
    environment {
        POSTGRES_SECRET = credentials('jenkins-postgres-credentials')
    }
    stages {
        stage('Update Packages') {
            steps {
                script {
                    // Update the package list
                    sh 'apt-get update'
                    sh 'apt-get install -y libpq-dev'
                }
            }
        }
        stage('Test') {
            steps {
                sh '''
                echo "User: $POSTGRES_SECRET_USR"
                echo "Pass: $POSTGRES_SECRET_PSW"
                # your commands here
                '''
            }
        }
        stage('Install Python') {
            steps {
                // Install Python and pip
                sh 'apt-get install -y python3 python3-pip python3-venv'
            }
        }
        stage('Clone Repository') {
            steps {
                script {
                    // Clone the Git repository
                    git branch: 'main', url: 'https://github.com/vaidotasEP/dqe-automation'
                }
            }
        }
        stage('Install and Run tests') {
            steps {
                script {
                    dir('PyTestDQFramework') {
                        sh '''
                            python3 -m venv venv
                            . venv/bin/activate
                            pip install --upgrade pip
                            pip install -r requirements.txt

                            export PYTHONPATH="$WORKSPACE/PyTestDQFramework"
                            python -m pytest tests -m "smoke or data_completeness or data_quality" \
                            --db_host=postgres --db_port=5432 \
                            --db_name=mydatabase --db_user="$POSTGRES_SECRET_USR" \
                            --db_password="$POSTGRES_SECRET_PSW" \
                            --html=html_report/report.html
                        '''
                    }
                }
            }
        }
        stage('Archive Test Report') {
            steps {
                // Archive the entire html_report directory, including assets
                archiveArtifacts artifacts: 'PyTestDQFramework/html_report/**', allowEmptyArchive: true

                // Publish the HTML report
                publishHTML(target: [
                            allowMissing: false,  // Fail the pipeline if the report is missing
                            keepAll: true,        // Keep all reports from previous runs
                            reportDir: 'PyTestDQFramework/html_report', // Correct directory path
                            reportFiles: 'index.html',                          // Entry point file
                            reportName: 'HTML Test Report'                      // Display name in Jenkins
                ])
            }
        }
    }
    post {
        always {
            echo 'Pipeline execution completed.'
        }
        success {
            echo 'Pipeline executed successfully!'
        }
        failure {
            echo 'Pipeline failed. Please check the logs for details.'
        }
    }
}
